name: 'release'
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - 30-renovation

jobs:
  build:
    env:
      VERSION: ${{ 1 }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install
        run: npm install
      - name: package
        run: npm run package
      - uses: EndBug/add-and-commit@v9
        if: github.ref == 'refs/heads/30-renovation'
        with:
          add: 'dist'
          push: false
      - name: Update major version tag (e.g., v1)
        # if: github.ref == 'refs/heads/main'
        if: github.ref == 'refs/heads/30-renovation'
        run: |
          git tag -f v${VERSION}
          git push --force origin refs/tags/v${VERSION}:refs/tags/v${VERSION}
