name: 'issue-tracer'
on:
  issues:
    types:
      - opened
      - edited

jobs:
  trace: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: |
      #     npm install
      # - run: |
      #     npm run all
      # - uses: actions/checkout@v2
      - uses: ./
        id: action
        env:
          ACTIONS_RUNNER_DEBUG: true
      - name: Get the output payload
        run: echo "The payload was ${{ steps.action.outputs.payload }}"
