name: 'issue-tracer'
on:
  issues:
    types:
      - opened
      - edited

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  detects:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          milliseconds: 1000
      - name: Get the output payload
        run: echo "The time was ${{ steps.action.outputs.payload }}"
